# version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: pgname # database name
      POSTGRES_USER: pguser # name of database user
      POSTGRES_PASSWORD: pgpassword # password for database user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000 # start server inside docker
    volumes:
      - ./backend:/web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  app:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  postgres_data: