# version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: pgname #database name
      POSTGRES_USER: pguser #name of database user
      POSTGRES_PASSWORD: pgpassword #password for database user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/web
    ports:
      - "8000:8000"

volumes:
  postgres_data: